/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CloudHubOmniTeam (https://sketchfab.com/cloudhub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electric-scissor-lift-1-4823e73dd2f94cbd9291b5d55df7f226
Title: Electric Scissor Lift 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Model1 = (props) => {
  const { nodes, materials } = useGLTF('/models/electric_scissor_lift_1.glb')
  const targetRef = useRef();
  useGSAP(() => {
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y + 0.5,
      duration: 1.5,
      repeat: -1,
      yoyo: true,
    });
  });



  return (
    <group {...props}  ref={targetRef} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.025}>
          <group position={[63.392, 136.335, 66.67]} rotation={[0, 0, -Math.PI / 2]}>
            <group position={[0, 1.063, 74.567]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_11.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_12.geometry}
                material={materials.MyFrontMaterial1}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_13.geometry}
                material={materials['0032_Moccasin']}
              />
            </group>
            <group position={[0, 2.992, 151.142]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_17.geometry}
                material={materials.MyFrontMaterial1}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials['0032_Moccasin']}
              />
            </group>
            <group position={[0, 5.354, 226.85]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_21.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials.MyFrontMaterial1}
              />
            </group>
            <group position={[41.89, 6.575, 226.85]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials.MyFrontMaterial1}
              />
            </group>
            <group position={[41.378, 3.036, 150.979]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_29.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.MyFrontMaterial1}
              />
            </group>
            <group position={[42.455, 1.335, 74.516]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_33.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials.MyFrontMaterial1}
              />
            </group>
            <group position={[41.566, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_37.geometry}
                material={materials['0032_Moccasin_0']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.MyFrontMaterial1}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials['0032_Moccasin']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.material}
            position={[0.619, 57.194, 398.075]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.209, 0.24, 0.24]}
          />
          <group
            position={[607.042, 397.386, 2.607]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, 0.62, 1]}>
            <group position={[-480.556, 509.392, -2.607]}>
              <group scale={0.152}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials.Color_002}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Color_002_0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.Color_008}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_52.geometry}
                material={materials.Color_004}
                position={[4.657, 0.381, 4.657]}
                scale={0.152}
              />
              <lineSegments geometry={nodes.Object_55.geometry} material={materials.material_0} />
              <lineSegments geometry={nodes.Object_56.geometry} material={materials['0.10.10.1']} />
              <lineSegments geometry={nodes.Object_57.geometry} material={materials['0.50.50.5']} />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_59.geometry}
                material={materials.Color_008}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials.Color_007}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_61.geometry}
                material={materials.Color_G16}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_62.geometry}
                material={materials.Color_C01}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_63.geometry}
                material={materials.Color_005}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_64.geometry}
                material={materials.Color_C01_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_65.geometry}
                material={materials.Color_004_0}
              />
            </group>
          </group>
          <group position={[481.294, -315.823, 2.607]} scale={[1, 0.62, 1]}>
            <group position={[-480.556, 509.392, -2.607]}>
              <group scale={0.152}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.Color_002}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_71.geometry}
                  material={materials.Color_002_0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.Color_008}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_75.geometry}
                material={materials.Color_004}
                position={[4.657, 0.381, 4.657]}
                scale={0.152}
              />
              <lineSegments geometry={nodes.Object_78.geometry} material={materials.material_0} />
              <lineSegments geometry={nodes.Object_79.geometry} material={materials['0.10.10.1']} />
              <lineSegments geometry={nodes.Object_80.geometry} material={materials['0.50.50.5']} />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_82.geometry}
                material={materials.Color_008}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_83.geometry}
                material={materials.Color_007}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_84.geometry}
                material={materials.Color_G16}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_85.geometry}
                material={materials.Color_005}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_86.geometry}
                material={materials.Color_004_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_87.geometry}
                material={materials.default_face_material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_88.geometry}
                material={materials.default_face_material8}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_89.geometry}
                material={materials.Color_G16_0}
              />
            </group>
          </group>
          <group
            position={[481.294, 397.386, 2.607]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, 0.62, 1]}>
            <group position={[-480.556, 509.392, -2.607]}>
              <group scale={0.152}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Color_002}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_95.geometry}
                  material={materials.Color_002_0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.Color_008}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_99.geometry}
                material={materials.Color_004}
                position={[4.657, 0.381, 4.657]}
                scale={0.152}
              />
              <lineSegments geometry={nodes.Object_102.geometry} material={materials.material_0} />
              <lineSegments
                geometry={nodes.Object_103.geometry}
                material={materials['0.10.10.1']}
              />
              <lineSegments
                geometry={nodes.Object_104.geometry}
                material={materials['0.50.50.5']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_106.geometry}
                material={materials.Color_008}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_107.geometry}
                material={materials.Color_007}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_108.geometry}
                material={materials.Color_G16}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_109.geometry}
                material={materials.Color_005}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_110.geometry}
                material={materials.Color_004_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_111.geometry}
                material={materials.default_face_material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_112.geometry}
                material={materials.default_face_material8}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_113.geometry}
                material={materials.Color_G16_0}
              />
            </group>
          </group>
          <group position={[607.042, -315.823, 2.607]} scale={[1, 0.62, 1]}>
            <group position={[-480.556, 509.392, -2.607]}>
              <group scale={0.152}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.Color_002}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_119.geometry}
                  material={materials.Color_002_0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials.Color_008}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_123.geometry}
                material={materials.Color_004}
                position={[4.657, 0.381, 4.657]}
                scale={0.152}
              />
              <lineSegments geometry={nodes.Object_126.geometry} material={materials.material_0} />
              <lineSegments
                geometry={nodes.Object_127.geometry}
                material={materials['0.10.10.1']}
              />
              <lineSegments
                geometry={nodes.Object_128.geometry}
                material={materials['0.50.50.5']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_130.geometry}
                material={materials.Color_008}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_131.geometry}
                material={materials.Color_007}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_132.geometry}
                material={materials.Color_G16}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_133.geometry}
                material={materials.Color_C01}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_134.geometry}
                material={materials.Color_005}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_135.geometry}
                material={materials.Color_C01_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_136.geometry}
                material={materials.Color_004_0}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_139.geometry}
            material={materials['0032_Moccasin']}
            position={[40.371, 62.447, 191.758]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_142.geometry}
            material={materials['0032_Moccasin']}
            position={[40.371, 14.73, 191.758]}
          />
          <group position={[0, 1.423, 344.386]}>
            <lineSegments geometry={nodes.Object_146.geometry} material={materials['1.00.40.0']} />
            <lineSegments geometry={nodes.Object_149.geometry} material={materials['1.00.40.0']} />
            <lineSegments geometry={nodes.Object_150.geometry} material={materials.material_0} />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_152.geometry}
              material={materials.Color_C01_0}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_155.geometry}
            material={materials['0032_Moccasin']}
            position={[42.104, 13.825, 187.478]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_158.geometry}
            material={materials['0032_Moccasin']}
            position={[37.46, 0.439, 32.015]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_161.geometry}
            material={materials.Color_C01_0}
            position={[141.718, 1.665, 36.549]}
            scale={[0.456, 0.456, 0.588]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_164.geometry}
            material={materials.Color_C01_0}
            position={[141.718, 78.437, 36.549]}
            scale={[0.456, 0.456, 0.588]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_167.geometry}
            material={materials.Color_C01_0}
            position={[3.743, 1.665, 37.139]}
            scale={[0.456, 0.456, 0.588]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_170.geometry}
            material={materials.Color_C01_0}
            position={[3.743, 78.437, 37.139]}
            scale={[0.456, 0.456, 0.588]}
          />
          <group position={[0.512, 1.266, 1.394]}>
            <lineSegments geometry={nodes.Object_174.geometry} material={materials['1.00.40.0']} />
            <lineSegments geometry={nodes.Object_177.geometry} material={materials['1.00.40.0']} />
            <lineSegments geometry={nodes.Object_180.geometry} material={materials['1.00.40.0']} />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_182.geometry}
              material={materials.Color_C01_0}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_183.geometry}
              material={materials.Color_C01}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_184.geometry}
              material={materials['0032_Moccasin_0']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_185.geometry}
              material={materials['0032_Moccasin']}
            />
          </group>
          <lineSegments geometry={nodes.Object_188.geometry} material={materials.material_0} />
          <lineSegments geometry={nodes.Object_189.geometry} material={materials['1.00.40.0']} />
          <lineSegments geometry={nodes.Object_190.geometry} material={materials['1.00.80.7']} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_192.geometry}
            material={materials.Color_C01_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_193.geometry}
            material={materials.default_face_material8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_194.geometry}
            material={materials.default_face_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_195.geometry}
            material={materials.Color_C01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_196.geometry}
            material={materials['0032_Moccasin_0']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_197.geometry}
            material={materials['0032_Moccasin']}
          />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/electric_scissor_lift_1.glb')

export default Model1;

